### ISSUE TITLE
Error message repeats on save

### ISSUE THREAD

**Issue by jbleyleSF** [arufian/LWC-Component-COVID19#4]
1. Create an Account with country USA. Save the record. Error message due to "US" issue.
1. Change country to United States. Save the record. The end of the error message repeats. 

>Please check this Account's Billing City or Country, and fill with correct value and **try to refresh the page and try to refresh the page****

![Screen Shot 2020-04-02 at 11 08 20 AM](https://user-images.githubusercontent.com/32077211/78283219-58345400-74d2-11ea-8ff2-fa2f2d0ddca7.png)

**Comment by arufian** [comment]
Hi @jbleyleSF 
~~Thank you for your first issue. This issue is related with issue #3 that you've created.
In the current version, the component only fetch the API on connectedCallback, which will only be triggered once.
Will work to solve this ASAP.~~

Sorry,  after I have investigated it, this issue is related with #2 .
Once the API fixed, it should be work.

**Comment by arufian** [comment]
The reason why the error message repeat, is because you were searching "USA" and  "United States", which both two didn't recognized by the API as a valid country.
I have added synonyms system to the API, so now it will recognize "USA", "United States" and "United States of America" as the synonyms of "US".

I will close this issue.
